name: Get MR Title


on: [pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test message
        run: echo "Hello world"

      - name: Bump the version
        id: mr_title
        run: bash bump_version.sh ${{ github.event.pull_request.title }}"
