name: Get MR Title

on:
  push

jobs:
  get_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get MR Title
        run: echo "Hello world"
