name: Pytest Check

on: 
  push:
    branches-ignore:
      - main

jobs:
  pytest-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Use the appropriate Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # Assuming you have a requirements file
          # You may need additional steps if pytest isn't installed already

      - name: Run pytest
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          pip3 install pytest
          pytest testing/

  attempt-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install node
      run: |
        cd frontend
        sudo apt install nodejs npm
        npm install -g create-react-app
        npm install react-scripts
        npm install

    - name: Lint the frontend code
      run: |
        cd frontend
        npm run build

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: yarn install
      - name: ESLint
        run: yarn run fix .
      - name: Prettier
        run: yarn prettier --write .
