name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Firebase credentials
        run: |
          echo "$FIREBASE_KEY" > credentials.json
          echo "$FIREBASE_URL" > firebase_url
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
      - name: Build the Docker image
        run: docker build -t jacobmacleod/flashcard-app:latest .
      - name: Log in to Docker Hub and push image
        run: |
          docker login -u jacobmacleod -p $DOCKER_PASSWORD
          docker push jacobmacleod/flashcard-app:latest
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      # Setup Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: your-project-id
          
      # Run a command on GCP VM via SSH
      - name: Run command on GCP VM
        run: |
          gcloud compute ssh prayer-prompts --command "echo 'Hello from GCP VM'"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: ["3.8", "3.9", "3.10"]
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pylint
#    - name: Analysing the code with pylint
#      run: |
#        pylint $(git ls-files '*.py')
