name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Firebase credentials
        run: |
          echo "$FIREBASE_KEY" > credentials.json
          echo "$FIREBASE_URL" > firebase_url
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
      - name: Build the Docker image
        run: docker build -t jacobmacleod/flashcard-app:latest .
      - name: Log in to Docker Hub and push image
        run: |
          docker login -u jacobmacleod -p $DOCKER_PASSWORD
          docker push jacobmacleod/flashcard-app:latest
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
      - uses: 'actions/checkout@v4'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
  
      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'prayer-prompts'
          zone: 'us-central1-a'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: 'echo Hello world'
  
      # Example of using the output
      - id: 'test'
        run: |-
          echo '${{ steps.build.outputs.stdout }}'
          echo '${{ steps.build.outputs.stderr }}'

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: ["3.8", "3.9", "3.10"]
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pylint
#    - name: Analysing the code with pylint
#      run: |
#        pylint $(git ls-files '*.py')
